import Head from 'next/head';
import React from 'react';
import Link from 'next/link';
import Image from 'next/image';

import { IconNetflix } from '~/components/icon';
import { publicRoutes } from '~/utils/constants/common';
import FormLogin from '~/components/FormLogin';

import bgNetflix from '~/assets/images/bgNetflix.jpg';

function Login() {
  return (
    <>
      <Head>
        <title>Netflix Login</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <div className="relative min-h-screen">
          <div className="absolute top-0 left-0 bottom-0 right-0 z-[-2]">
            <Image src={bgNetflix} alt={bgNetflix.src} className="object-cover w-full h-full" priority />
            <div className="absolute top-0 left-0 bottom-0 right-0 bg-[rgba(0,0,0,.4)] z-[0] bg-start-page"></div>
          </div>
          <div className="flex items-center pt-5">
            <div className="flex items-center justify-between w-full pt-2 mx-14">
              <Link href={publicRoutes.index} className="text-red-500 !h-[36px]">
                <IconNetflix height={36} />
              </Link>
            </div>
          </div>
          <FormLogin />
        </div>
      </div>
    </>
  );
}

export default Login;
